<?php
/** @var Letsrock_PromoTabs_Block_Display $this */
  $tabs = $this->getTabs();
?>

	<script src="http://sideful.ru/adverti-slider/js/jcarousel.js"></script>
	<script src="http://sideful.ru/adverti-slider/js/mobile.js"></script>
	<div class="adv-slider">
		<div class="core">
			<div class="tab" data-tab="1">
				<h5>Заголовок текстового таба</h5>
				<p class="more"><a href="#">Еще</a></p>
				<div class="info-text">
					<p>It's enough. This is still the best way. You go after him with a gun, you'll never get out of it alive. But with this... you slip it into his food or drink, there shouldn't be any taste or smell... thirty-six hours later... poof. A man his age, working as hard as he does... no one will be surprised. Mike can have his suspicions, but that's all they'll be. Please, one homicidal maniac at a time.</p>
					<p>Look, I'll give you Jesse Pinkman, OK? Like you said, he's the problem, he's always been the problem and without him, we would... and he's in town, alright? He's not in Virginia or wherever the hell you're looking for him. He's right here in Albuquerque and I can take you to him, I'll take you right to him. What do you say?</p>
					<p>It's complicated and I don't wish to discuss it. It's none of your concern. You know what, let's just say that I have a hell of a lot more on my mind, right now, than thinking about buying a damn car wash. Okay? So if you could just... please.</p>
					<p>Stop. Stop! You keep saying that word - danger... danger! No and I have never used that word. I said things were complicated. And then you flew off the handle!</p>
				</div>
			</div>
			<div class="tab" data-tab="2">
				<h5>Заголовок таба со списком ссылок</h5>
				<div class="listing">
					<ul>
						<li>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники, Antonio Veronesi</a></p>
							<p><a href="#">Ежедневники и еженедельники Nazarenogabrielli Nazarenogabrielli Nazarenogabrielli</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
						</li>
						<li>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники, Antonio Veronesi</a></p>
							<p><a href="#">Ежедневники и еженедельники Nazarenogabrielli Nazarenogabrielli Nazarenogabrielli</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
						</li>
						<li>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники, Antonio Veronesi</a></p>
							<p><a href="#">Ежедневники и еженедельники Nazarenogabrielli Nazarenogabrielli Nazarenogabrielli</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
						</li>
						<li>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники, Antonio Veronesi</a></p>
							<p><a href="#">Ежедневники и еженедельники Nazarenogabrielli Nazarenogabrielli Nazarenogabrielli</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
						</li>
						<li>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники, Antonio Veronesi</a></p>
							<p><a href="#">Ежедневники и еженедельники Nazarenogabrielli Nazarenogabrielli Nazarenogabrielli</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
						</li>
						<li>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники, Antonio Veronesi</a></p>
							<p><a href="#">Ежедневники и еженедельники Nazarenogabrielli Nazarenogabrielli Nazarenogabrielli</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
						</li>
						<li>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники, Antonio Veronesi</a></p>
							<p><a href="#">Ежедневники и еженедельники Nazarenogabrielli Nazarenogabrielli Nazarenogabrielli</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
						</li>
						<li>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники, Antonio Veronesi</a></p>
							<p><a href="#">Ежедневники и еженедельники Nazarenogabrielli Nazarenogabrielli Nazarenogabrielli</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
						</li>
						<li>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники, Antonio Veronesi</a></p>
							<p><a href="#">Ежедневники и еженедельники Nazarenogabrielli Nazarenogabrielli Nazarenogabrielli</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
						</li>
						<li>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники</a></p>
							<p><a href="#">Ежедневники и еженедельники, Antonio Veronesi</a></p>
							<p><a href="#">Ежедневники и еженедельники Nazarenogabrielli Nazarenogabrielli Nazarenogabrielli</a></p>
							<p><a href="#">Ежедневники и еженедельники</a></p>
						</li>
					</ul>
				</div>
			</div>
			<div class="tab" data-tab="3">
				<h5>Заголовок таба с карточками товаров</h5>
				<div class="products">
					<ul>
						<li>
							<a href="#">
								<div>
									<img src="http://sideful.ru/adverti-slider/img/watermark_265x265_1.png" alt="">
								</div>
								<h6><span>Зонт-трость «Форсайт», механический</span></h6>
								<p>592,73 руб.</p>
								<span class="more"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<div>
									<img src="http://sideful.ru/adverti-slider/img/907178-210_1.jpg" alt="">
								</div>
								<h6><span>Зонт-трость «Форсайт», механический</span></h6>
								<p>592,73 руб.</p>
								<span class="more"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<div>
									<img src="http://sideful.ru/adverti-slider/img/watermark_265x265_1.png" alt="">
								</div>
								<h6><span>Зонт-трость «Форсайт», механический</span></h6>
								<p>592,73 руб.</p>
								<span class="more"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<div>
									<img src="http://sideful.ru/adverti-slider/img/907178-210_1.jpg" alt="">
								</div>
								<h6><span>Зонт-трость «Форсайт», механический</span></h6>
								<p>592,73 руб.</p>
								<span class="more"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<div>
									<img src="http://sideful.ru/adverti-slider/img/watermark_265x265_1.png" alt="">
								</div>
								<h6><span>Зонт-трость «Форсайт», механический</span></h6>
								<p>592,73 руб.</p>
								<span class="more"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<div>
									<img src="http://sideful.ru/adverti-slider/img/907178-210_1.jpg" alt="">
								</div>
								<h6><span>Зонт-трость «Форсайт», механический</span></h6>
								<p>592,73 руб.</p>
								<span class="more"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<div>
									<img src="http://sideful.ru/adverti-slider/img/watermark_265x265_1.png" alt="">
								</div>
								<h6><span>Зонт-трость «Форсайт», механический</span></h6>
								<p>592,73 руб.</p>
								<span class="more"></span>
							</a>
						</li>
						<li>
							<a href="#">
								<div>
									<img src="http://sideful.ru/adverti-slider/img/907178-210_1.jpg" alt="">
								</div>
								<h6><span>Зонт-трость «Форсайт», механический</span></h6>
								<p>592,73 руб.</p>
								<span class="more"></span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<ul class="nav">
			<li class="active"><a href="1">Текстовый таб</a></li>
			<li><a href="2"><img src="http://sideful.ru/adverti-slider/img/nav-icon.png" width="19" height="18" alt=""> Список категорий</a></li>
			<li><a href="3">Карточки товаров</a></li>
		</ul>
	</div>




<div class="sliders-in-col clearfix">
    <div class="sliders-in-col__left-w">
        <div class="sliders-in-col__left">

            <div class="promo-slider js-promo-slider">
                <ul class="promo-slider__inner">
                    <?php foreach($tabs as $tab) {?>
                        <li>
                            <div class="promo-slider__content promo-slider__content_<?php echo $tab->getType();?>">
                                <div class="promo-slider__content__header clearfix">
                                    <div class="promo-slider__content__title fleft"><?php echo $tab->getTitle();?></div>
                                    <?php if($tab->getLink() && $tab->getLabelLink()){?>
                                            <a href="<?php echo $tab->getLink()?>" class="fright"><?php echo $tab->getLabelLink()?> &raquo;</a>
                                    <?php }?>
                                </div>
                                <?php
                                switch ($tab->getType()) {
                                    case "tab_text":?>
                                            <div class="content_tab_text">
                                                <?php echo $tab->getContent();?>
                                            </div>
                                       <?php
                                        break;
                                    case "tab_products":?>
                                            <div class="promo-product-w">
                                                <?php foreach($this->getProducts($tab->getContent()) as $product) { ?>
                                                    <?php
                                                    Mage::helper('calculate')->isDiscounted($product);
                                                    ?>
                                                    <a href="<?php echo $product->getUrlKey().'.html' ?>" class="promo-product">
                                                        <?php if($product->getData('recommended_price_old')) {?><div class="discount-flag">скидка</div><?php }?>
                                                        <?php if($product->getData('archive')) {?><div class="archive-flag">Архивный товар</div><?php }?>
                                                        <div class="promo-product__image-w">
                                                            <img class="promo-product__image promo-product__image_max-height" src="<?php  echo $this->helper('catalog/image')->init($product, 'small_image')->resize(210)->setQuality(100); ?>"
                                                                 alt=""/>
                                                        </div>
                                                        <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                                                            <div class="promo-product__title"><?php echo $product->getName() ?></div>
                                                        </div>
                                                        <div class="promo-product__price">
                                                            <?php if($product->getData('recommended_price_old')) {?>
                                                                <span class="catalog_oldprice"><?php echo number_format($product->getData('recommended_price_old'), 2, ',', ' ');?></span>
                                                            <?php }?>
                                                            <?php echo number_format($product->getData('recommended_price'), 2, ',', ' ');?>&nbsp;руб.
                                                        </div>
                                                    </a>
                                                <?php } ?>
                                            </div>
                                        <?php
                                        break;
                                    case "tab_categories":?>
                                        <div class="content_tab_categories">
                                            <ul>
                                            <?php foreach($this->getCategories($tab->getContent()) as $category) { ?>
                                                   <li><a href="<?php echo $category->getUrlPath();?>"><?php echo $category->getName();?></a></li>
                                            <?php }?>
                                            </ul>
                                        </div>
                                        <?php
                                        break;
                                }
                                ?>
                            </div>
                        </li>
                    <?php } ?>

                </ul>
                <div class="promo-slider__controls">
                    <?php foreach($tabs as $tab) {?>
                        <div class="promo-slider__controls__item">
                            <a class="promo-slider__controls__link" data-id="<?php echo $tab->getId();?>" href="#">
                                <?php if($tab->getImage()!="") {?>
                                     <img src="../media/<?php echo $tab->getImage();?>">
                                <?php }?>
                                <?php echo $tab->getTitle();?>
                            </a>
                        </div>
                    <?php } ?>
                </div>
            </div>

        </div>
    </div>


    <?php if (count($this->getItemForPromo())): ?>
        <div class="sliders-in-col__right">
            <div class="adaptive-slider adaptive-slider_vertical-in-one js-adaptive-slider-top">
                <div class="discount-flag">Скидки</div>

                <div class="adaptive-slider__pages-info">
                    <span class="adaptive-slider__pages-info__pages"></span>
                    <span class="delimeter"></span>
                    <a href="#" class="adaptive-slider__pages-info__tobegin dotted">В начало</a>
                </div>
                <!--<ul class="adaptive-slider__inner"></ul>-->
                <!-- сюда вставляются слайды из заготовки <div class="adaptive-slider__content"></div> -->
                <div class="adaptive-slider__premade">
                    <?php foreach ($this->getItemForPromo() as $discountProduct): ?>

                        <a href="<?php echo Mage::getBaseUrl().$discountProduct->getData('url_path') ?>" class="promo-product promo-product_adaptive-slider promo-product1">
                            <div class="promo-product__image-w">
                                <img class="promo-product__image" src="<?php  echo $this->helper('catalog/image')->init($discountProduct, 'small_image')->resize(210)->setQuality(100); ?>"
                                     alt=""/>
                            </div>
                            <div class="promo-product__title-w promo-product__title-w_hidden-1-col promo-product__title-w_hidden-2-col">
                                <div class="promo-product__title"><?php echo $discountProduct->getName() ?></div>
                            </div>
                            <div class="promo-product__price">
                                <div class="promo-product__price__oldprice"><?php echo $discountProduct->getOldPrice() ?><!--<span class="rouble">a</span>-->&nbsp;руб.</div>
                                <div class="promo-product__price__price"><?php echo $discountProduct->getPriceLow() ?><!--<span class="rouble">a</span>-->&nbsp;руб.</div>
                            </div>
                            <div class="promo-product__additional">при тираже&nbsp;<?php echo $discountProduct->getPromoCount() ?> шт.</div>
                        </a>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    <?php endif;?>

</div>
    <script>
        jQuery(function() {
            //выбираем какой слайд показывать в слайдере на главной странице по дефолту, задается из админки
            var slideId = '<?php echo $this->getActiveTab();?>';
            var slideIndex = promoSlider.elements.controls().filter('[data-id=' + slideId + ']').parent().index();
            window.promoSlider.init( slideIndex);
        });
    </script>

